### ISSUE TITLE
How 'magic' works

### ISSUE THREAD

**Issue by nmay231** [JoCaNo-Productions/flat-land#2]
How exactly will 'Magic' work? Clearly, `Player.mana` will be the currency and `Player.magic_regen` the speed of mana regen (should we change the name to that: `mana_regen`). However, the following confuses me as to their exact usage:
- `Player.magicpower`
- `Player.magicresist`
Clearly, the second determines resistance to magic, but will be it multiplicative (e.g. 0.5 *magic_damage) or additive (magic_damage - 3).
I don't have an idea of what the first does. What does it do?

**Comment by nmay231** [comment]
Hey @calebmrose00

**Comment by calebmrose00** [comment]
they are both multiplicative and they both effect magic.
the Player.magicpower is the positive multiplayer for the caster of the ability. eg more attack damage, more health, ect.
the Player.magicresist reduces negative effects such as damage or slow

**Comment by calebmrose00** [comment]
also feel free to add, or change variable names to make them more clear

**Comment by calebmrose00** [comment]
Hey @nmay231

**Comment by nmay231** [comment]
Got it @calebmrose00.
