### ISSUE TITLE
Champ.end_of_turn

### ISSUE THREAD

**Issue by nmay231** [JoCaNo-Productions/flat-land#9]
I think the main purpose of this method is to apply health regen, mana regen, etc. to a champion's attributes. It also needs to decrement all of the "until" values (`.until_attack`, `.until_health_regen`) unless they are already zero. All of the `champ.mods.turn` methods need to be called as well.

**Comment by nmay231** [comment]
If you just want me to work on this, let me know in the Coordination issue.

**Comment by nmay231** [comment]
@calebmrose00 
I'll go ahead and claim work on the `champ.end_of_turn()` thing. **DON'T START WORK ON IT PLEASE.**

**Comment by calebmrose00** [comment]
k

**Comment by nmay231** [comment]
@calebmrose00 
Just finished it.
